import PageAnimatePresence from '@/components/HOC/page-animate-presence';
import { NavTabs } from '@/components/nav-tabs';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <header className="flex justify-center p-4">
            <NavTabs />
          </header>
          <main className="grow p-4 flex justify-center items-center">
            <PageAnimatePresence>{children}</PageAnimatePresence>
          </main>
        </div>
      </body>
    </html>
  );
}
